DROP TABLE IF EXISTS HR_EMPLOYEE;
  
CREATE TABLE HR_EMPLOYEE (
  id VARCHAR(50) NOT NULL  PRIMARY KEY,
  login VARCHAR(250) NOT NULL,
  name   VARCHAR(250) NOT NULL,
  salary Double NOT NULL,
  start_date DATE NOT NULL
);